name: dngn-landing
region: ams3
domains:
  - domain: dngn.org
    type: ALIAS
    wildcard: false
  - domain: www.dngn.org
    type: ALIAS
    wildcard: false
  
static_sites:
  - name: landing
    environment_slug: html
    github:
      repo: staa99/dngn
      branch: main
    source_dir: landing-site
    index_document: dist/index.html
    routes:
      - path: /site